### ISSUE TITLE
2 issues related to branches

### ISSUE THREAD

**Issue by kroussevrb** [phrase/phraseapp-ruby#48] opened 2020-06-27 04:27 UTC
1. I didn't find anywhere in the documentation support for the following command of the main client `$ phrase push --use-local-branch-name
`

2. when I create a branch via `phraseapp-ruby` and then delete it from the Phrase web app, all consecutive attempts to create the branch again fail with `not found`

Additionally, trying to upload to a branch randomly fails. I tested listing the locales for the main branch and for the new branch, and I got the correct locales for main, but an empty list for my branch (although in the web app they can be seen, and they have different ids than the ones in main)

I am using locale name for all these tasks, as suggested in the "Using branches" documentation: https://help.phrase.com/help/branches ("Do I need to change my .phrase.yml config file when working with branches?")

**Comment by rlisowski** [comment] 2020-06-30 06:49
Hi @kroussevrb  

thanks for the report.

1. `phrase push` command is a combination of few API endpoints such as branches, locales and uploads. You can find details  in [source code](https://github.com/phrase/phrase-cli/blob/master/cmd/internal/push.go#L28)

2. I will look into this one. Do you have a minimal sample code that will allow me to reproduce this?

Creating a branch takes some time. So when you create a branch and immediately ask for locales list it will be empty. Make sure the branch state is `success` https://developers.phrase.com/api/#branches_show

**Comment by kroussevrb** [comment] 2020-06-30 07:01
Actually I just received a response from Phrase support and they said issue 2 was caused by the fact that deleting a branch doesn't delete it fully from the DB, and this causes the failures, they said they were going to fix it.

Thanks for the "success" tip, I'll make sure to implement it. At one point I had the code wait for 5 seconds just to make sure, but it still wasn't working. I am pretty sure the problem was the forementioned one that is going to get fixed.

**Comment by rlisowski** [comment] 2020-06-30 07:44
ok @kroussevrb so should we close this issue since it seems to be related to API backend and is already proceed by Phrase support?

**Comment by kroussevrb** [comment] 2020-06-30 07:47
I think so, if there's anything else, I'll ping you. Sorry!

**Closed** 2020-07-01 11:40 UTC

**Comment by kroussevrb** [comment] 2020-12-31 07:06
@rlisowski 
A while ago you said:

```
Creating a branch takes some time. So when you create a branch and immediately ask for locales list it will be empty. Make sure the branch state is success https://developers.phrase.com/api/#branches_show
```

Now that `phraseapp-ruby` is deprecated and we can migrate to `phrase-ruby`, is the new api still asynchronous, or upon the branch creation api response, we are now guaranteed that the branch is fully created, and we can proceed with the next operation on it, or do we again have to wait for some time and check if it's been created with a separate api call?

**Comment by theSoenke** [comment] 2021-01-04 07:15
@kroussevrb The API is still behaving in the same way with phrase-ruby and you would have to wait til the branch has been successfully created before you can start working with it

**Comment by kroussevrb** [comment] 2021-01-04 07:16
Thank you!
